### ISSUE TITLE
PS5_solutions: function to create variables for estimation

### ISSUE THREAD

**Issue by jdebacker** [jdebacker/CompEcon_Fall21#42]
Create a function in `PS5_solutions.py` to create variables needed to determine the payoff matrices.  This function should take a dataframe as an argument and then return a dataframe with all variable needed for analysis.  Something like what is done on lines 10-15 of the current file, but perhaps with more variables created.

**Comment by amshoulders** [comment]
Hi @jdebacker should this still be open? Was this not resolved by my latest PR?

**Comment by jdebacker** [comment]
@amshoulders Yes, while there has been progress, I'm keeping this open because there can be improvements.  e.g., see my code snippet above. One need note create and return 4 DataFrames/arrays from the function.  Rather one should be calling the function 4 times, returning one object each time.
