### ISSUE TITLE
PS5 Solutions: more efficient code for arrays of matches

### ISSUE THREAD

**Issue by jdebacker** [jdebacker/CompEcon_Fall21#45]
`PS5_Solutions.py` now has a function called `create_array_ids`, which creates arrays of buyer and target ids that will be useful for creating the payoff matrices however, this function could be written in a better way:

1. There are multiple nested for loops over the same ranges.  This can all be done in just one nested for loop
2. Use Numpy array objects -- not lists and DataFrames.

**Comment by Joy-liningqiao** [comment]
By referring to the existing data structure in create_array_ids function, I wrote the following codes:

df07=df07[['year', 'buyer_id','target_id']]
df08=df08[['year', 'buyer_id','target_id']]

list1 = []
list3 = []

for seq in df07['buyer_id']:
    # create the column for real buyers list1
    list1.append([seq] *  (len(df07) - seq))
    # create the counterfact for counterfactual buyers
    list3.append(range(seq + 1, len(df07) + 1))

# flatten the two lists
list1 =list(np.concatenate(list1).flat)
list3 =list(np.concatenate(list3).flat)

list2, list5, list8 = list1, list1, list1 
list4, list6, list7 = list3, list3, list3
list0 = ['2007'] *len(list1)

df_result = pd.DataFrame(data = np.array([list0, list1, list2, list3, list4, 
                                          list5, list6, list7, list8]).T)
df_result.columns =['year', 'buyer', 'target', 'buyer_prime', 'target_prime', 'buyer',
                    'target_prime', 'buyer_prime', 'target']
df_result

**Comment by Joy-liningqiao** [comment]
I don't know why the note "flatten the two lists" was shown in such a bold way. It is just a note with # actually.
I do have a question about constructing the matches structure, let's take 2007 for example, for the real pair (2,2), why there is no counterfactual pair of (1,1)? Also for the real pair (3, 3), why there are no corresponding counterfactual pairs of (1,1) and (2, 2)?

**Comment by jdebacker** [comment]
@Joy-liningqiao writes:
> I don't know why the note "flatten the two lists" was shown in such a bold way. It is just a note with # actually.

Github comments use [markdown](https://www.markdownguide.org) formatting.  In markdown, the hash sign is used for headings.

@Joy-liningqiao then asks:
> I do have a question about constructing the matches structure, let's take 2007 for example, for the real pair (2,2), why there is no counterfactual pair of (1,1)? Also for the real pair (3, 3), why there are no corresponding counterfactual pairs of (1,1) and (2, 2)?

Now one can use different notation, but what we've followed is that the tuple represents a buyer and target id (e.g., (buyer 1, target 1)).  Since our data have just  one to one matches, we've chosen to denote these actual matches as (1, 1), (2, 2), (3, 3), etc where we give buyers and targets the same id number in the actual matches.  

This means that counterfactuals will have matches where the buyer and target id differ.  e.g, (1, 2) and (2, 1) are both counterfactual matches (target 1 actually matched with buyer 1 and target 2 with buyer 2).

With N = 3 actual matches, we have (N-1)*N/2 = 3 combinations of actual and counterfactual matches to compare in our score estimator (without transfers):

(1, 1) + (2, 2) >= (1, 2) + (2, 1)
(1, 1) + (3, 3) >= (1, 3) + (3, 1)
(2, 2) + (3, 3) >= (2, 3) + (3, 2)

**Comment by Zilin-Xiong** [comment]
Great array making, I learned how to do data frame from your codes.
