### ISSUE TITLE
PS5 Solutions: Score function

### ISSUE THREAD

**Issue by jdebacker** [jdebacker/CompEcon_Fall21#51]
Create a function that returns the score.  This function should take as arguments:

1. Arrays or data frames of buyer/target characteristics (corresponding to the matches on each side of the inequality)
2. Parameters (e.g., beta)
3. Maybe other optional keyword arguments 

It should return a scalar that is the value of the score function.

There should be no loops inside this function.

**Comment by kstrohl** [comment]
I included below some of what I had originally had, which is a start? Since we don't need loops, I'm not sure what would be the best way to reference what we need - maybe use the column index of each characteristic needed? It's probably also possible to create this function without also having to define the payoff function, but as I was doing that it seemed like a super long line of code. 

`def score_fn(params): 
    '''
    Args:
        params: initial guesses for model parameters (alpha and beta)
    Returns:
        score: maximum score estimation
    '''
    alpha, beta = params
    score = 0
    
    def payoff_fn(dataframe, index):
        '''
        Args:
            dataframe: dataframe of buyer and target characteristics (corresponding to matches)
            index: identification numbers for radio station b and target t
        Returns:
            payoff: the payoff to the merger between radio station b and target t in market m
        '''
        b, t = index

        payoff = dataframe.num_stations_buyer[b] * dataframe.scaled_pop[t] + alpha * dataframe.corp_owner_buyer[b] * dataframe.scaled_pop[t] + beta * dataframe.distance_mi[]
        return(payoff)

    if payoff_fn(dataframe=df, index=(i, i)) + payoff_fn(dataframe=df, index=(j, j)) > payoff_fn(dataframe=counterfacts, index=(i, j)) + payoff_fn(dataframe=counterfacts, index=(j, i)): 
        score += 1
    return(score)`

**Comment by Zilin-Xiong** [comment]
The first objective function doesn't work. For line 253, "counter_sum = counter.loc[counter['payoff'][j]] + counter.loc[counter['payoff'][j-1]]", should we change the j-1 into j+1 ?
