### ISSUE TITLE
PS5 Solutions: docstrings and comment formatting

### ISSUE THREAD

**Issue by jdebacker** [jdebacker/CompEcon_Fall21#52]
Add descriptive docstrings to all functions.  Please follow the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).  Keep all lines in docstrings (or in-line comments) to no more than 88 characters.

**Comment by Joy-liningqiao** [comment]
Good morning, Professor, thanks for the new open issues. I wondered do you want us directly to write the docstring in PS5_solutions.py file?

**Comment by Zilin-Xiong** [comment]
@Joy-liningqiao I think maybe we can write the docstrings here, indicating which line we would like to add.
